@echo off
REM Interactive Installation Script for Windows
REM Run this to set up multi-agent-assistant with all dependencies

setlocal enabledelayedexpansion

cd /d "%~dp0"

REM Colors and formatting
set "BLUE=[94m"
set "GREEN=[92m"
set "YELLOW=[93m"
set "RED=[91m"
set "BOLD=[1m"
set "RESET=[0m"

title Multi-Agent Assistant - Installation

cls
echo.
echo ============================================================
echo Multi-Agent Assistant - Interactive Setup
echo ============================================================
echo.
echo This script will set up your assistant with:
echo   * GitHub account and personal access token
echo   * GitHub Models API ^(AI brain^)
echo   * Gmail integration ^(optional^)
echo   * Profile configuration
echo.
echo Requirements: Python 3.11+, Git, pip
echo.
pause

REM Check Python version
echo.
echo [1] Checking Python version...
python --version >nul 2>&1
if errorlevel 1 (
    echo ERROR: Python not found. Install Python 3.11+ from python.org
    pause
    exit /b 1
)

for /f "tokens=2" %%i in ('python --version 2^>^&1') do set PYVER=%%i
echo Python version: %PYVER%
echo.

REM Check dependencies
echo [2] Checking system dependencies...
where git >nul 2>&1
if errorlevel 1 (
    echo WARNING: Git not found. Install from git-scm.com
) else (
    echo Git: Found
)

where pip >nul 2>&1
if errorlevel 1 (
    echo WARNING: pip not found. Install Python packaging tools.
) else (
    echo pip: Found
)
echo.

REM Install backend dependencies
echo [3] Installing Python dependencies...
cd services\orchestrator
pip install -q -r requirements.txt
if errorlevel 1 (
    echo ERROR: Failed to install dependencies
    pause
    exit /b 1
)
echo Python dependencies installed.
cd ..\..
echo.

REM GitHub setup
echo [4] GitHub Account Setup
echo.
echo GitHub is needed for GitHub Models API ^(free LLM brain for your assistant^).
echo.
set /p has_github="Do you already have a GitHub account? (y/n): "
if /i not "%has_github%"=="y" (
    echo Please visit https://github.com/signup
    echo   1. Create account
    echo   2. Verify email
    echo   3. Return here
    echo.
    pause
)

REM GitHub token
echo.
echo [5] GitHub Personal Access Token
echo.
echo Steps to generate token:
echo   1. Go to https://github.com/settings/tokens
echo   2. Click 'Generate new token (classic)'
echo   3. Fill in:
echo      - Token name: multi-agent-assistant
echo      - Expiration: 90 days
echo      - Scopes: Check ONLY 'read:models'
echo   4. Click 'Generate token'
echo   5. Copy the token
echo.
set /p GITHUB_TOKEN="Paste your GitHub token: "

if "%GITHUB_TOKEN%"=="" (
    echo ERROR: GitHub token required
    pause
    exit /b 1
)
echo.

REM Gmail setup
echo [6] Gmail Setup (Optional)
echo.
set /p setup_gmail="Do you want to set up Gmail integration? (y/n): "

set GMAIL_ENABLED=false
set GMAIL_FROM=
set GMAIL_PASSWORD=

if /i "%setup_gmail%"=="y" (
    set /p has_gmail="Do you have a Gmail account? (y/n): "
    if /i not "%has_gmail%"=="y" (
        echo Please visit https://gmail.com to create one
        pause
    )
    
    echo.
    echo Steps for app-specific password:
    echo   1. Go to https://myaccount.google.com/security
    echo   2. Enable 2-Step Verification
    echo   3. Go to https://myaccount.google.com/apppasswords
    echo   4. Select 'Mail' and 'Windows Computer'
    echo   5. Copy the 16-character password
    echo.
    set /p GMAIL_FROM="Enter your Gmail address: "
    set /p GMAIL_PASSWORD="Paste the app-specific password: "
    set GMAIL_ENABLED=true
)
echo.

REM Profiles
echo [7] Create Assistant Profiles
echo.
echo Assistant Profile:
set /p ASSISTANT_EMAIL="Assistant email (default: assistant@example.com): "
if "%ASSISTANT_EMAIL%"=="" set "ASSISTANT_EMAIL=assistant@example.com"

echo.
echo Boss ^(Your^) Profile:
set /p BOSS_NAME="Your name (default: User): "
if "%BOSS_NAME%"=="" set "BOSS_NAME=User"

set /p BOSS_EMAIL="Your email (default: user@example.com): "
if "%BOSS_EMAIL%"=="" set "BOSS_EMAIL=user@example.com"

set /p BOSS_TIMEZONE="Your timezone (default: UTC): "
if "%BOSS_TIMEZONE%"=="" set "BOSS_TIMEZONE=UTC"

echo.
echo Enter your goals (one per line, empty line to finish):
set "GOALS="
for /l %%i in (1,1,3) do (
    set /p GOAL="  Goal %%i (optional): "
    if not "!GOAL!"=="" (
        set "GOALS=!GOALS!,"!GOAL!"
    )
)
if not "!GOALS!"=="" set "GOALS=!GOALS:~1!"

echo.
echo Enter your constraints (one per line, empty line to finish):
set "CONSTRAINTS="
for /l %%i in (1,1,3) do (
    set /p CONSTRAINT="  Constraint %%i (optional): "
    if not "!CONSTRAINT!"=="" (
        set "CONSTRAINTS=!CONSTRAINTS!,"!CONSTRAINT!"
    )
)
if not "!CONSTRAINTS!"=="" set "CONSTRAINTS=!CONSTRAINTS:~1!"

REM Write .env file
echo.
echo [8] Writing configuration...

(
    echo # Generated by installation script
    echo APP_ENV=dev
    echo APP_HOST=0.0.0.0
    echo APP_PORT=8000
    echo GITHUB_TOKEN=%GITHUB_TOKEN%
    echo GITHUB_MODELS_ENABLED=true
    echo GITHUB_MODELS_MODEL=gpt-4o-mini
    echo GITHUB_MODELS_TIMEOUT=30
    echo ASSISTANT_EMAIL_ENABLED=%GMAIL_ENABLED%
    echo ASSISTANT_EMAIL_FROM=%GMAIL_FROM%
    echo ASSISTANT_EMAIL_APP_PASSWORD=%GMAIL_PASSWORD%
    echo NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api/v1
    echo EXPO_PUBLIC_API_BASE_URL=http://localhost:8000/api/v1
) > .env

echo .env file created.

REM Create data directory and profiles
if not exist data mkdir data

(
    echo {
    echo   "assistant_name": "multi-agent-assistant",
    echo   "email": "%ASSISTANT_EMAIL%",
    echo   "version": "0.1.0",
    echo   "skills": [
    echo     {"skill": "planning", "level": "advanced", "description": "Goal setting and roadmap creation"},
    echo     {"skill": "scheduling", "level": "advanced", "description": "Calendar management"}
    echo   ],
    echo   "supported_agents": ["planner", "calendar", "finance", "wellness", "general"],
    echo   "instructions": "Be concise and actionable.",
    echo   "guardrails": []
    echo }
) > data\assistant_profile.json

echo Profiles created.
echo.

REM Summary
cls
echo.
echo ============================================================
echo Installation Complete!
echo ============================================================
echo.
echo Configuration saved to:
echo   * .env ^(environment variables^)
echo   * data/assistant_profile.json
echo   * data/boss_profile.json
echo.
echo Next steps:
echo.
echo 1. Start the backend:
echo    cd services\orchestrator
echo    python -m uvicorn app.main:app --reload
echo.
echo 2. In another terminal, start the web frontend:
echo    cd apps\web
echo    npm install
echo    npm run dev
echo.
echo 3. Visit http://localhost:3000
echo.
echo Test the setup:
echo    python test_quick.py --verbose
echo.
echo Documentation:
echo    * INSTALLATION.md - Setup guide
echo    * docs/TESTING.md - Testing reference
echo    * docs/github_models_setup.md - GitHub Models details
echo.
pause
